### PR TITLE
Strengthen "Motivations" sections: Part 3c #854

### PR DESCRIPTION
**Pull request by eaquin1**
I worked on the motivation sections for javascript-6-object-literals.md, runtime-complexity.md, and basic-js-practice.md. This is my first contribution to open source, so please let me know what I can improve upon! Thank you!

### CODE REVIEW

**Comment by alodahl** [comment]
Why did you close this? It was really close

**Comment by eaquin1** [comment]
Oh, sorry if it was incorrect to close it! When I made the corrections, it
was posted as a secondary pull request, and I thought that the changes were
accepted on that new pull request (#1073).  Since I'm new to open source,
I'm not really sure how to keep it all as one pull request (perhaps it was
because I made a new branch when I implemented your suggestions).  Sorry
again, and I really appreciate all your guidance in this project!

**Comment by alodahl** [comment]
No, if they are accepted, you would get an "approved" message, and if it has been incorporated, the PR would be marked as "Merged" instead of "closed". This is alright, but in the future, you can just commit to the same branch and push, and the changes will appear in the same PR.

**Comment by alodahl** [comment]
Do I need to keep these changes too for your next PR to make sense?  You would have to open it back up; I don't have access.

**Comment by alodahl** [comment]
fixes #854

**Comment by eaquin1** [comment]
@alodahl, everything I have worked on has been merged. Thanks again for all your explanations, and hard work!

**Pull request merged**
