### PR TITLE
Formatted all the techtonica templates at issue #600

### PR DESCRIPTION
**Pull request by imskr**
All the slides having access to me I have formatted. Fixed issue #600

### CODE REVIEW

**Comment by alodahl** [comment]
Mentors, please choose 5 slideshows at random in #598 and make sure they follow the format mentioned. If it doesn't, please comment about it. @Shwetha-Acharya @hoduchieu01 @Kundan28

**Comment by imskr** [comment]
Its in #600 @alodahl

**Comment by Kundan28** [comment]
Okay @alodahl . Will review it today itself.

**Comment by Shwetha-Acharya** [comment]
Hi Alina, I will review it by tomorrow.

**Comment by Kundan28** [comment]
@alodahl I have reviewed slideshows 62, 65, 69, 71 and 75.
**Slideshow 62**
_The only thing I figured out was that almost every slide's regular text was not ending with a full stop(.)_

**Slideshow 65**
In the slide no. 10, 11 and 12 the font size of the regular content is 14 it should be 18 or 24.
And this slideshow too don't have full stop(.) after end of the lines.

**Slideshow 69**
This slideshow was not having any issue.

**Slideshow 71**
In the slide no. 2, 3, 4, 5 and 9 the font size of the regular content is 20, it should be 18 or 24.
And in the slide no. 7 the heading size is 26, it should be 28.
And this slideshow too don't have full stop(.) after end of the lines.

**Slideshow 71**
This slideshow too don't have full stop(.) after end of the lines and rest of the things were fine.

**Comment by imskr** [comment]
@Kundan28 I only have to edit fonts and not to add ". " in slides as per issue #600

**Comment by Kundan28** [comment]
> @Kundan28 I only have to edit fonts and not to add ". " in slides as per issue #600

I know that but I am just informing @alodahl so that if it should be added then she would tell you otherwise just make the other changes I mentioned.

**Comment by imskr** [comment]
@Kundan28 in some slides text size can't be 18 or 24 because of text overflow. It goes out of the slides.

**Comment by Kundan28** [comment]
@imskr One more slide could be added if you want to follow the pattern.

**Comment by alodahl** [comment]
> @Kundan28 in some slides text size can't be 18 or 24 because of text overflow. It goes out of the slides.

Resolve this by spreading the info across multiple slides with the same header

**Comment by Kundan28** [comment]
> Resolve this by spreading the info across multiple slides with the same header @imskr

Yeah, I said the same to @imskr

**Comment by imskr** [comment]
@Kundan28 edited those slides as you have mentioned.

**Comment by Kundan28** [comment]
@imskr In the Slideshow 65 I think that some steps should be on this slide no. 11 and the other could be on the other one. As the slide 11 seems incomplete.

**Comment by Shwetha-Acharya** [comment]
I have checked slides: 77, 78, 79, 80 and 81.
To go with mentioned criteria, slides seem fine. One thing I noticed is, the text size, which is either preferred to be 18 or 24. 
It is not strictly followed. 
@imsk please check if you can make up to the mentioned criteria of font size.

**Comment by alodahl** [comment]
@Shwetha-Acharya did you notice which slideshows need to have font sizes fixed?

**Comment by Shwetha-Acharya** [comment]
These are the nit picks, interms of mentioned criteria, not major short comings :) @imskr @alodahl 

**Slide 77**:  page 8 (font size: 20) 

**Slide 78**:  all pages (font size: 20)
	             except page 16 (font size: 24)

**Slide 79:** Page 15 (font size: 16)
                    Page 16 (font size: 16)

**Slide 80**: Page 7 (font size: 22)

**Slide 81**: Seems fine.

**Comment by imskr** [comment]
Should i fix text issues to all slides ? This will need to add more slides to each @alodahl .

**Comment by Kundan28** [comment]
> Resolve this by spreading the info across multiple slides with the same header @imskr

Yes @imskr go for it. @alodahl had already told you that.

**Comment by alodahl** [comment]
Thanks @imskr, I know there’s a lot to look at. I agree with all the changes mentors have asked for. Periods should be added to slideshow 71 for consistency, and we have rules about font size for accessibility, and to limit the amount of text in a slide so it’s not overwhelming.

**Comment by imskr** [comment]
@alodahl It was little tough for me but I have edited all the slides again according to the requirements except 2-3 which i didn't had permission. If there is any error please report.

**Comment by alodahl** [comment]
@Kundan28 @Shwetha-Acharya are you able to look again?  @hoduchieu01 @saberprashant could you have a look too? See my reviewing directions near the top.

**Comment by Kundan28** [comment]
Yeah @alodahl  , will definitely have a look again.
And I think the reviewing directions are in https://github.com/Techtonica/curriculum/issues/600

**Comment by Kundan28** [comment]
@alodahl I have looked again Slideshow 62, 65, 69, 71 & 72 and commented the required changes in the respective slides.

**Comment by imskr** [comment]
@Kundan28 I don't have access to those.

**Comment by imskr** [comment]
@Kundan28 And the full stop (.)  Isn't required as it is not mentioned in original issue.

**Comment by imskr** [comment]
@Kundan28 Please check  the issue #600 I do not have to fix typos or image clarity problems. I only have to fix font & text size issues.

**Comment by Kundan28** [comment]
> @Kundan28 And the full stop (.) Isn't required as it is not mentioned in original issue.

https://github.com/Techtonica/curriculum/pull/739#issuecomment-484151294

**Comment by Kundan28** [comment]
> @Kundan28 Please check the issue #600 I do not have to fix typos or image clarity problems. I only have to fix font & text size issues.

I have seen that but I just mean that if you can do it then it's good for all of us as we don't have to just create a new issue for just fixing typos and punctuation marks.

**Comment by alodahl** [comment]
@imskr please fix typos (part of formatting... the issue list is not exhaustive), but since you did not make the slideshow you are not responsible for clear pictures.  @Kundan28 can you be specific here about which photos need to be better?  Maybe we can make an issue for that.

**Comment by imskr** [comment]
@Kundan28 ok I will try to fix the typos.

**Comment by Shwetha-Acharya** [comment]
@imskr Please make the font **size 18** in the **slide 8** of  **slide show 77**. 
Also add period at the end of sentences in mentioned slides:
**Slide show 77**: slide no - **2, 5, 8, 10 and 14 (under algorithm optimization)**
**Slide show 80**: Slide no - **7 (first two points)** 
@alodahl I am seeing error while playing the videos in slideshow 79, except for the video in slide 4. Please have a look at it. May be a new PR?

**Comment by imskr** [comment]
@alodahl @Kundan28 @Shwetha-Acharya I have edited slides, fixed some typos, and added punctuation. some functions were too long so i left its font size as it is.  Slides i don't have access: 66, 67, 68, 69, 70, 91.

**Comment by Shwetha-Acharya** [comment]
I see that all of my comments are addressed! Good job!!! in Slide show 77, please remove period **under Asynchronous I/O (input/output** of slide 14. We dont use an exclamatory mark and period one after the other!

**Comment by Kundan28** [comment]
> @alodahl @Kundan28 @Shwetha-Acharya I have edited slides, fixed some typos, and added punctuation. some functions were too long so i left its font size as it is. Slides i don't have access: 66, 67, 68, 69, 70, 91.

Full stop is not required after the links in slide number 28 of slideshow 62.

**Comment by Kundan28** [comment]
In slideshow 72, in the first page there is exclamation mark and period at the same place. So fix that.

**Comment by Kundan28** [comment]
And remove the fullstop after the links.

**Comment by imskr** [comment]
ok got it.

**Comment by imskr** [comment]
@Shwetha-Acharya @Kundan28 Done 😅

**Comment by alodahl** [comment]
Sorry you didn’t have access, @imskr . I just gave you access to 66, 67, & 70.

I don’t have access to 68, 69, or 91 either... don’t worry about it.  They look good anyway.

**Comment by Kundan28** [comment]
> I don’t have access to 68, 69, or 91 either... don’t worry about it. They look good anyway.

I had reviewed slideshow 69 by making a copy of that and I found that everything is good in that.

**Comment by alodahl** [comment]
@Shwetha-Acharya I checked out slideshow 79, and it just says that I need to be in present mode to see the videos. Does this answer your question, or does it tell you you don’t have permission?

**Comment by alodahl** [comment]
Mentors, please approve PR if the slides look good to you.

**Comment by Kundan28** [comment]
> Mentors, please approve PR if the slides look good to you.

Okay.

**Comment by alodahl** [comment]
Thank you for fixing our lessons @imskr!

**Comment by Kundan28** [comment]
Updated on score sheet too. 🙌

**Pull request merged**
