### PR TITLE
replace dead link 'growth mindset quiz' to a working alternative

### PR DESCRIPTION
**Pull request by DrQue99**
This is an alternative link that Zarina recommended on Slack to replace the old link that leads to a down web-page.

### CODE REVIEW

**Comment by alodahl** [comment]
Thanks Quincey! Maybe Bill or Kisha told you in person to merge this, but in general allow your code to be reviewed before merge.

**Comment by Q-up** [comment]
Great! Thanks Alina. Will I see you Tuesday at the JavaScript study group?

**Comment by alodahl** [comment]
Aditi is leading next week, but I’m sure I’ll see you soon 😊

**Comment by Q-up** [comment]
Alrighty, have a great weekend!

**Pull request merged**
