### PR TITLE
final changes made to apprenticeship-prep folder

### PR DESCRIPTION
**Pull request by atrip10**
Resolves issue #1250 
The required changes have been to the folder

### CODE REVIEW

**Comment by alodahl** [comment]
No more deleting branches until it’s merged! And next time work on a new branch, not master.

**Comment by alodahl** [comment]
Go ahead and resolve your conflicts, too.

**Comment by alodahl** [comment]
Hey @Kundan28 she went and deleted it, so I guess it’s this PR

**Comment by atrip10** [comment]
> Is socioeconomic differences not in the readme?

No it isn't there

**Comment by atrip10** [comment]
> No more deleting branches until it’s merged! And next time work on a new branch, not master.

Okay I will keep this in mind

**Comment by atrip10** [comment]
> Go ahead and resolve your conflicts, too.

How to resolve this conflict

**Comment by atrip10** [comment]
> Go ahead and resolve your conflicts, too.

How to resolve the conflict

**Comment by atrip10** [comment]
once again fork it and clone and make the required changes?

**Comment by alodahl** [comment]
Don’t worry about the conflicts until you are done with everything else.

**Comment by alodahl** [comment]
> > Is socioeconomic differences not in the readme?
> 
> No it isn't there

@vegetabill shouldnt it be in the readme?

**Comment by atrip10** [comment]
> follow the directions below to resolve conflicts. Are you able to just press the resolve conflicts button?

yes i can press the button
readme.md files open in github showing me one conflice

**Comment by alodahl** [comment]
I'd recommend making a new branch and not working off of master in the future. This is fine for now, but it will complicate things if you try to work on another issue before this one is merged.

**Comment by alodahl** [comment]
Rule of thumb:  if you are making the change on purpose, keep your branch's change.  If you do not remember making that change, then choose the master change.

**Comment by Kundan28** [comment]
> Hey @Kundan28 she went and deleted it, so I guess it’s this PR

Okay, I got it.

**Comment by alodahl** [comment]
@Kundan28 it is not in the readme in the first place.  I asked @vegetabill if this is intentional. But otherwise I think this is ready.

**Comment by atrip10** [comment]
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

Thank you so much for your help i have resolved the conflict and sorry for being so late in completing this task

**Comment by alodahl** [comment]
Great job being persistent!  We ran into some weird problems.

**Comment by atrip10** [comment]
> Great job being persistent! We ran into some weird problems.

Thank you @alodahl ma'am and @Kundan28 sir

**Comment by Kundan28** [comment]
> > Great job being persistent! We ran into some weird problems.
> 
> Thank you @alodahl ma'am and @Kundan28 sir

Most welcome.

**Comment by Kundan28** [comment]
Updated the scoresheet.

**Pull request merged**
