### PR TITLE
Updated the lists to remove paras.

### LINKED ISSUE #1277: Unify the lists and spacing in Readme.md
The lists in the main Readme.md has a lot of spaces making it inconsistent with others. It should be unified. This is more of a cosmetic change than a content change.

### PR DESCRIPTION
**Pull request by praveenscience**
Fixes #1277

* Most of the lists had line spaces in this.
* Removed the line spacing so no new paragraphs inside list are created.

> **Note:** I am a mentor previously so thought of just helping out this particular one. 😊

### CODE REVIEW

**Comment by praveenscience** [comment]
Thanks a lot! 😅🙏🏻

**Comment by Kundan28** [comment]
I think @praveenscience you should try becoming participant next time. You would definitely be in the top of list.

**Comment by praveenscience** [comment]
@Kundan28 That'd be illegal dude... I am a decade experienced... 😅

**Comment by Kundan28** [comment]
That's great to hear. Which one is your project ?

**Pull request merged**
