### PR TITLE
Add resource for beginners about functional programming

### PR DESCRIPTION
**Pull request by jdq22**
The link I added is an awesome resource I found a few years back. It's interactive, so it's great for getting immediate results on whether or not your solution is correct.

### CODE REVIEW

**Comment by jdq22** [comment]
There are 41 exercises, and I'd imagine each exercise would take ~15 minutes. This resource is meant to be "go at your own pace." This can be used as an advanced "check for understanding" or as a beginner's exercise.

**Comment by jdq22** [comment]
@alodahl I'll add more info to the file about the resource in terms of "what to expect."

**Comment by jdq22** [comment]
@alodahl Please let me know what you think about the additional copy!

**Comment by alodahl** [comment]
This will be very good for apprentices to know.  Thank you Jenna!!

**Pull request merged**
