### PR TITLE
Issue #2112 - Creates comparing testing frameworks outline

### PR DESCRIPTION
**Pull request by stmcpeters**
Description: 
for this issue, I have been assigned to update the comparing testing frameworks outline in the curriculum to: 
- clarify the differences between the various testing frameworks (e.g RTL, Vitest, Jest, Supertest, etc)
- provide examples/use cases for when to use each testing frameworks
- include necessary configuration or setup steps required for each testing framework to work properly within the project environment

Objective: 
- what is your PR doing and how does it provide a solution for your issue
- how does the code in your PR hope to accomplish
- what are your changes doing

### CODE REVIEW

**Comment by stmcpeters** [comment]
awaiting access to view the current testing framework comparison sheet by staff

**Comment by stmcpeters** [comment]
**Description** 
This issue was created because it may not be clear to participants when to use the various testing frameworks (ex. RTL, Jest, Vite, Supertest)

**Objective** 
I have made the following changes/additions in this PR:
- created a topic outline that clarifies the differences between RTL, Jest, Vite, Supertest & best use cases to use each.
- provided questions to check participant understanding of testing frameworks (ex. What is the difference between unit and integration testing?)
- added a supplemental material section at the end with videos provided in the pre-existing testing framework day doc
- added additional sections such as, prerequisites, motivation, etc. with additional information
- described the composition of a test suite and provided an example with explanatory code comments

**Questions/Room for Improvement**
- Leveraging the information from the provided day doc, the Chai and Mocha frameworks were grouped together, rather than separated. Was this done purposefully, or should they be separated in the topic outline in order to clearly explain their differences?
- In this topic outline draft, I just briefly mentioned mocking and stubbing to avoid overloading participants with information for an initial introduction to testing frameworks

I would appreciate any tips or suggestions to help improve this outline further, especially regarding the clarity of the framework comparisons and the balance of detail provided. Let me know if any sections could be expanded, or if there's anything that should be simplified or reorganized to enhance participant understanding 😸

**Review by daaimah123 — APPROVED** [review]
🥳

the curriculum originally taught chai and mocha testing together so they were grouped together

**Comment by stmcpeters** [comment]
sounds good, i'll leave it as-is. thank you for the feedback!

**Pull request merged**
