### PR TITLE
Fix markdown formatting in lesson outline #1031

### PR DESCRIPTION
**Pull request by kirschstern**
Hi,
please have a look at my solution to this markdown problem: I did not changed the numbers as wished, but I had to put some extra spaces to the codeblock, otherwise the ordered list will not continue with the count.
Hope I could help you with this issue!

### CODE REVIEW

**Comment by alodahl** [comment]
Hi @kirschstern , this looks great!  Could you have a look at the markdown preview and tweak some of the inconsistent indenting?  Once you do that, I can merge.

**Comment by kirschstern** [comment]
Hi, 
now it should work as you wished :)

**Comment by alodahl** [comment]
I’d like to give someone else a chance to solve this, so I will move it back to to-do on Saturday if there are no changes by then.

**Comment by kirschstern** [comment]
Hi,
now the code should be correctly indented.

**Comment by alodahl** [comment]
fixes #1031

**Pull request merged**
