### PR TITLE
Update data-visualization.md

### PR DESCRIPTION
**Pull request by achhunna**
Need to update Things to Remember to Check for Understanding

### CODE REVIEW

**Comment by MichelleGlauser** [comment]
Thanks, Achhunna!

**Comment by achhunna** [comment]
@Karla-Isabel-Sandoval I updated the Data Visualization slides with D3 and SVG stuff. Could you review and make changes as necessary? I think it needs some graphics or visual examples, which I couldn't think of. Thanks!

**Comment by Karla-Isabel-Sandoval** [comment]
Thank you so much @achhunna! Will take a look at the slides.

**Comment by Karla-Isabel-Sandoval** [comment]
@achhunna thank you for your work on the DV slides! You mentioned that you were going to get rid of chart.js and it looks like the slides still contain chart.js slides and references. Did you mean to keep those there?

**Comment by achhunna** [comment]
@Karla-Isabel-Sandoval I left a link on chart.js in the "More Data Visualization Resources" just as additional things to look at. Chart.js uses canvas element so is quite different from D3. We can remove it if you think it might be confusing.

**Comment by Karla-Isabel-Sandoval** [comment]
@achhunna I mentioned chart.js because it looks like slides 4 - 7 are still about chart.js? we can keep both of them, was just under the impression that you wanted to remove them?

**Comment by achhunna** [comment]
@Karla-Isabel-Sandoval I deleted them, are we looking at the same slides? [Link](https://docs.google.com/presentation/d/1qgFhrP5u70UgsTe_khB9nrUnlq-17zY4yjPzSphPCW8/edit#slide=id.p)

**Comment by Karla-Isabel-Sandoval** [comment]
@achhunna I was looking at https://docs.google.com/presentation/d/1Vzx0eyKt0jNQq70pnAeDQ5X1qOPdjIzCgujSp6dd_1U/edit#slide=id.g25118499e6_0_29 originally.

**Comment by achhunna** [comment]
@Karla-Isabel-Sandoval Seeing that file for the first time. I didn't make those changes.

**Comment by Karla-Isabel-Sandoval** [comment]
Weird! Yes, the slides I was looking at were completely different than the ones you sent me. The ones you updated look great. Thank you!!

**Comment by achhunna** [comment]
Sure thing. The other slides look good too, maybe you can combine both.

**Pull request merged**
