### PR TITLE
Issue #2113 - Audit week 1 and 2 projects

### PR DESCRIPTION
**Pull request by stmcpeters**
I have made the following changes to the week 2 project outline and attached a screenshot taken prior to making changes:
- fixes spelling typo in the title (method → methods)
- fixes punctuation typos under Languages section
- removes JS from overview section (students will be incorporating JS in this phase of the project)
Screenshot 2024-12-12 at 1 58 26 PM

### CODE REVIEW

**Comment by stmcpeters** [comment]
hey @ChasVanDav, do you mind looking this over and leaving any feedback :)

**Comment by ChasVanDav** [comment]
@stmcpeters I will give your pr a once over and let you know any suggestions by EOD today!

**Review by ChasVanDav — APPROVED** [review]
These grammar corrections and clarifying changes look good to me!

**Comment by thisIsTheWei** [comment]
LGTM

**Review by daaimah123 — APPROVED** [review]
@stmcpeters I have approved your changes. Your audit looks good!

- Please acknowledge and "resolve" any outstanding comments that you have not interacted with.
- Please let me know if you have any additional incoming changes. If not, go ahead and "Merge pull request".
- Ensure both your related GH issue and PR status have been appropriately updated to "Implemented or Addressed" (this should happen automatically, but if not do so manually).
- Leave a respective comment on your related GH issue closing it.

**Comment by stmcpeters** [comment]
thank you everyone for your value feedback! I will merge this issue

**Pull request merged**
