### PR TITLE
typos in 2_conditionalsExercise

### PR DESCRIPTION
**Pull request by picaq**
on line 154 change the first duplicate `EXCERCISE 8` to `EXCERCISE 7` to match with `excercise7()`
on line 181 change `amount 1` to `amount1` to match the parameters on `excercise8()`

### CODE REVIEW

**Review by alodahl — APPROVED** [review]
Thanks Mandy 😄

**Comment by alodahl** [comment]
Want to practice resolving conflicts so I can merge this?

**Comment by picaq** [comment]
Since I forked the curriculum instead of cloning it a long time ago, I’m not sure if this would update the file found on the main curriculum.

**Comment by alodahl** [comment]
Congrats on making it in, Mandy 🤸🏼‍♀️

**Pull request merged**
