### PR TITLE
Additions to ethics.md

### PR DESCRIPTION
**Pull request by jennifro**
- Added an Independent Practice exercise to brainstorm about an ethical problem & approach to resolve.
- Added real example to Privacy section re: teen girl's pregnancy being revealed to her parents via ads.
- Added to Human & Machine Bias. 
- Added consideration to Agency that managers may not consider ethics before assigning tasks.

### CODE REVIEW

**Comment by alodahl** [comment]
@jennifro , would you be open to creating a slideshow based on the Ethics outline? https://docs.google.com/presentation/d/1nPC_2vFCjBgStTJP_Edpfu_37LAIhJEVARfob56wLp4/edit?usp=sharing

**Comment by jennifro** [comment]
Alina,

Yes I would! I'll work on it tomorrow.

Jennifer Dixon

**Comment by alodahl** [comment]
Hi @jennifro, how is the slideshow coming along?  Do you need anything?

**Comment by jennifro** [comment]
I didn't see the due date before, my apologies. I watched the video &
reviewed the materials in the outline. I'll try to have the slideshow
finished this weekend.

- Jennifer

**Comment by alodahl** [comment]
Thank you Jennifer!

**Comment by alodahl** [comment]
@jennifro I just wanted to check in about the ethics slideshow.  Do you need a break, or do you think you'll have time for it this week?

**Pull request merged**
