### PR TITLE
Fixed links in README.md (#1282)

### LINKED ISSUE #1282: Fix links in README.md file
https://github.com/Techtonica/curriculum/blob/master/README.md

Some of the links in the README.md file give 404 errors since the paths to the resources are incorrect. For example: **Whiteboarding** link under **Independent Topics**   

I am a GSSoC 20 participant and I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Tahanima**
Closes #1282 

1. Fixed broken links
2. Changed the text **Resources: Women in Tech** to **Resources: Underrepresented in Tech** under Week 14 - Project Prep Week & Electives

Please review the changes and let me know if there is anything I need to add/change.

### CODE REVIEW

**Comment by Kundan28** [comment]
@alodahl Have a look at this.

**Comment by vegetabill** [comment]
@Kundan28 please don't repeat comments. We don't use comments in our workflow so it will not make us see this faster.

**Comment by Kundan28** [comment]
> @Kundan28 please don't repeat comments. We don't use comments in our workflow so it will not make us see this faster.

Okay, my apology.

**Comment by Kundan28** [comment]
Updated in scoresheet too.

**Pull request merged**
