### PR TITLE
separate supplemental resources 

### LINKED ISSUE #570: separate supplemental resources from required materials. (multiple assignees encouraged)
On one side, some apprentices think that they need to throughly look through every material, and are getting way behind because of it.  On the other, many well-meaning volunteers have thrown the kitchen sink into the "materials" section, when many or even all of them should be considered "supplemental resources" (supplemental meaning additional, extra, not required). 

Look through topic outlines, and change one so that:
- the "slides" are part of the "materials" section
- the "lesson" explicitly directs how to use the mandatory "materials" (ex: "Read through [these slides]() )
- optional materials are under a "supplemental resources" section.
- if you finish, or notice a topic outline looks fine, please check it off on this list or let a Techtonica admin know it's complete.

Topic outlines whose materials sections not been reviewed:
- [x] https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
- [x] https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md

- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/html/html.md

- [x] https://github.com/Techtonica/curriculum/blob/master/git-version-control/gitignore.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/css/css.md

- [x] https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
- [x] https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
- [x] https://github.com/Techtonica/curriculum/blob/master/bootstrap/bootstrap.md
- [x] https://github.com/Techtonica/curriculum/blob/master/professionalism/building-confidence.md

- [x] https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md
- [x] https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md
- [x] https://github.com/Techtonica/curriculum/blob/master/deploying/deploying-1-personal-site.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md

- [x] https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/runtime-complexity.md
- [x] https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/jasmine-testing.md
- [x] https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md
- [x] https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md
- [x] https://github.com/Techtonica/curriculum/blob/master/react-js/react.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/intro-to-data-structures.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/stack.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/deque.md

- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/searching.md
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/sorting.md

- [x] https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md

### PR DESCRIPTION
**Pull request by ronika-das**
fixes #570 

i moved slides to "Materials" sections
and "Supplemental Materials" at the very end of topic outline

### CODE REVIEW

**Comment by ronika-das** [comment]
hey @alodahl , this is a branch yet all previous commits are being shown. I was hoping if you could squash the commits from your end though i will still work on it.
and please let me know any changes for this PR

**Comment by ronika-das** [comment]
hey @alodahl  . I apologise for asking again. I did exactly this.
Actually my master is showing, 39 Commits ahead of techtonica/master and when i create any subsequent branch, is shows 43 commits ahead of techtonica/master(39 from my master branch+ 4 from my newly created branch)
the problem is with my master branch. any suggestions on how to rectify that?

**Comment by alodahl** [comment]
I actually encountered this at work today. My next guess would be to checkout master, git add and git stash any changes you might have, git reset —hard, which should ensure you’re at “head” (aka most recent commit), then git pull. If that all works out, THEN check out a brand new branch that you’ve never made before or have deleted first, and put your changes there for the PR. Let me know if that helps.

**Comment by ronika-das** [comment]
hey @alodahl . I tried the method you suggested and a couple others.  It is not giving the desired result. should I delete my repo and fork it again? i will ensure i work on branches correctly. but will i lose my gssoc points?

**Comment by alodahl** [comment]
Have you tried merging the original repo to your fork before making your new branch? Ask how to do this on the git channel if you’re not sure, but I’m guessing you are not keeping your fork updated, so it’s showing all the differences.

**Comment by alodahl** [comment]
You will not lose your points, just keep trying 🧘🏻‍♀️

**Comment by alodahl** [comment]
Another tactic: save your pr files somewhere, delete your fork locally and remotely, and make a new fork before moving on.

**Comment by alodahl** [comment]
Don’t give up! This is a pretty common and confusing problem that I and a coworker actually had last week... real world stuff.  💪👩‍💻

**Comment by alodahl** [comment]
@ronika-das, if you don’t fix this PR in the next few days, we will close we this PR. You will need to make a new or valid PR for this issue before you can pick up a new one.

If I don’t hear from you, we may give this issue to someone else, since it’s been idle for so long.
@Shwetha-Acharya @manaswinidas @saberprashant  @hoduchieu01 @Kundan28

**Comment by Kundan28** [comment]
@ronika-das If you need any help you can ask here.

**Comment by alodahl** [comment]
@ronika-das you can use your branch to try making another PR, but I am closing this one.

**Comment by alodahl** [comment]
I recommend saving your 3 file somewhere, then
```
git checkout master 
git pull
git checkout -b <new branch name here>
```
then put your 3 changed files in and make a PR.

**Comment by Kundan28** [comment]
I have removed this PR from Scoresheet too.

**Pull request closed without merging**
