### PR TITLE
modified movie goers function

### PR DESCRIPTION
**Pull request by yati1998**
Fixes Issue #569

### CODE REVIEW

**Comment by yati1998** [comment]
Yes this is work in progress.

**Comment by alodahl** [comment]
@yati, what results will you get with the new requirements?

**Comment by yati1998** [comment]
I haven't set the new requirements. The only thing we can do is.  Set the output to none in the case of ambiguity.  Or A new problem if we can exchange.

**Comment by alodahl** [comment]
@yati1998 can you change the rules for the people in the problem so there is less confusion, please?

**Comment by alodahl** [comment]
Also, once you finish this issue, you can pick up another one.

**Comment by yati1998** [comment]
@alodahl ohk sure.

**Comment by yati1998** [comment]
> Is this a work in progress PR?

The current commit solves the issue.

**Pull request merged**
