### PR TITLE
#560

### PR DESCRIPTION
**Pull request by Rita-Okonkwo**

### CODE REVIEW

**Comment by alodahl** [comment]
@Rita-Okonkwo provide your issue number in the description and resolve your conflicts below. If your not sure how, there are lots of searchable resources online.

**Comment by Rita-Okonkwo** [comment]
Hi @saberprashant yes I'm unable to resolve the conflict and would really appreciate every help I can get . Thanks alot

**Comment by alodahl** [comment]
Thanks @saberprashant.  @rita, we still need your issue number and a description of your changes.

**Comment by alodahl** [comment]
My first impression is that you have conflicts because you did not make a new branch from the latest master before working on this new PR.  There are commits listed that I doubt are part of your issue. I’d save your changes somewhere like your desktop, and start over.

**Comment by saberprashant** [comment]
Hi @Rita-Okonkwo, as @alodahl said, you might forget to pull down the latest changes from the master branch and that's why these conflicts came.
The best ways to avoid such situations are:
1. Make a new branch always for whatever a new change you wanna do on your local end(make it from master, use, `git checkout -b <newBranchName> <fromBranch> `
2. Do take a pull(like, `git pull origin master`) to this branch always before pushing your branch to your repo.

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl @saberprashant I'M REALLY CONFUSED. I tried resolving the conflict by creating a new branch and pushing my changes to the new branch. But the conflict is still there. Im really confused

**Comment by saberprashant** [comment]
Hi @Rita-Okonkwo , it is really great that you are trying. This is the best thing actually. Cheers :)

And congrats, I resolved all of your conflicts and now your branch has no issue and is ready to be merged. :)

Now to answer your question, as you made a new branch and pushed your changes to that, then I think you forgot to take a pull using "git pull origin master" to that branch. Now when I looked into your changes, I found that the content you wrote in this section `Mailing Lists, Google or Facebook Groups, and Slacks:` in file `curriculum/women-in-tech-resources/resources-list.md` was wrong. Due to this, conflicts occurred. So, always try to edit at the right place.

And please read more about resolving conflicts here:
https://www.git-tower.com/learn/git/ebook/en/command-line/advanced-topics/merge-conflicts

**Comment by alodahl** [comment]
Hi @rita-okonkwo, I think once you pull the updates from master (it changes almost every day), the changes tab will only show the changes you’ve made recently, rather than having “explain nano”, etc. You can do it!

**Comment by Rita-Okonkwo** [comment]
Thanks alot @alodahl @saberprashant for your help so far. I really appreciate you all

**Comment by saberprashant** [comment]
Hi @Rita-Okonkwo , please tell us the issue number which you solved because I am unable to find a running issue with contents you changed. If there is no running issue as such, then you can create an issue and provide the description for the changes required and then reference this PR in that issue.

Thanks :)

**Comment by Kundan28** [comment]
@saberprashant I think the issue number is #560

**Comment by alodahl** [comment]
This is fine, @Rita-Okonkwo , the changes look good.  Before you start your next issue, be sure to git checkout master, git pull, and git checkout -b <new-branch-name> so you dont have to worry about many conflicts =)

**Comment by saberprashant** [comment]
Thanks, @Kundan28, for letting me know of the issue number 😄

**Comment by Kundan28** [comment]
> Thanks, @Kundan28, for letting me know of the issue number 😄

Most welcome. 😇

**Pull request merged**
