### PR TITLE
Correction of slides: issue 1198

### PR DESCRIPTION
**Pull request by abhu-A-J**
address #1198 

Based on the changes made in resolving issue #1197 , the necessary changes have been made to their respective slides .Making a PR with a single typo fix as instructed on the issue.

### CODE REVIEW

**Comment by Kundan28** [comment]
@alodahl From where would I get the links to the slides ?
@abhu-A-J If you could help me find that ?

**Comment by abhu-A-J** [comment]
@Aayush-1999 I have mentioned the changes on Issue itself since it was mentioned to do it that way on the issue. You can check that.

I'll do the Loops Slides as well. It seems I missed that out . Thanks!

**Comment by Kundan28** [comment]
@alodahl Do @abhu-A-J don't have to follow #600 here ?

**Comment by alodahl** [comment]
@kundan28 the issue is only to have the slides match the outline mentioned in #1197 ‘s PR. No new formatting is necessary.

**Comment by abhu-A-J** [comment]
> could you keep the word "topic" and fix the word "Prerquisites" instead? 😇

@alodahl Ma'am I have made the changes!

**Pull request merged**
