### PR TITLE
translated any mySQL info to PostgreSQL

### PR DESCRIPTION
**Pull request by ANURADHAJHA99**

### CODE REVIEW

**Comment by ANURADHAJHA99** [comment]
@alodahl I have made the new PR as required.

**Comment by alodahl** [comment]
Can you please explain what this PR is? Did you both change MySQL to postgresQL AND move chilunguy’s filed into Techtonica?

**Comment by ANURADHAJHA99** [comment]
@alodahl yes the following PR solves the following issue https://github.com/Techtonica/curriculum/issues/595

**Comment by ANURADHAJHA99** [comment]
@alodahl It translates all the mySQL info to PostgresSQL and as required I moved the working folder to the the project folder.

**Comment by ANURADHAJHA99** [comment]
@alodahl It translates all the mySQL info to PostgreSQL and as required I moved the working folder to the the project folder.

**Comment by ANURADHAJHA99** [comment]
@alodahl I have added the required change.

**Comment by alodahl** [comment]
Closes #595

**Comment by alodahl** [comment]
Fixes #595

**Pull request merged**
