### PR TITLE
Formatted all the slides as per guidelines

### PR DESCRIPTION
**Pull request by imskr**
Formatted Techtonica Slideshows at issue #598 . I have edited all the slides as per instructions. Slide no 12, 26 is ok as told by @alodahl. Slide no 30 is not available to me.

### CODE REVIEW

**Comment by imskr** [comment]
@Kundan28 @manaswinidas @Shwetha-Acharya Please review this.

**Comment by imskr** [comment]
@Kundan28  I have made the changes in 9 and 20.

**Comment by Shwetha-Acharya** [comment]
@alodahl Please give edit access to mentors, it will be easier to review.

**Comment by alodahl** [comment]
Mentors, let me know which slideshows you'd like to look at and I will give you access.

**Comment by alodahl** [comment]
@praveenscience you were able to look at the slideshows in the issue?

**Comment by alodahl** [comment]
@Kundan28 no need to assess slideshow 1, 3, 12, 26,  or 30.  The other slideshows should be available to you.  Thanks for your help!

**Comment by Kundan28** [comment]
@alodahl I have reviewed all the Slideshows. So sorry for the delay...I am a bit busy with University Exams and documentation.
@imskr I have commented the changes to be made in the slides.

**Comment by imskr** [comment]
Done @Kundan28 i have rechecked and edited all the slides. Please check.

**Comment by alodahl** [comment]
@kundan28 no worries, thank you for doing it!

**Comment by imskr** [comment]
Is there anything I have to change?  @alodahl

**Comment by Kundan28** [comment]
> Is there anything I have to change? @alodahl

I am checking all the slides once again

**Comment by alodahl** [comment]
Nice work Shubham!  I have a question for you, please check slack 😊

**Pull request merged**
