### PR TITLE
Formatted Techtonica Slides 2/3

### PR DESCRIPTION
**Pull request by imskr**
Formatted all the slides present at #599 according to guidelines.

### CODE REVIEW

**Comment by Kundan28** [comment]
@alodahl I only have edit access to only 35, 36, 37, 40, 45, 50. So I have reviewed these six slideshows.
@imskr In the six slideshows I reviewed, only in slideshow 37 changes are required. I have commented the changes to be made.

**Comment by imskr** [comment]
Thanks @Kundan28 I have made changes to it. And please note that i dont have access to **32 & 53**

**Comment by Kundan28** [comment]
@alodahl Thanks for the edit access to all the slides.
@imskr I have reviewed all the slides and commented the changes to be made. Once you are done with that, comment down and I will review all the slides again and approve this PR.

**Comment by imskr** [comment]
@Kundan28 Thank you for reviewing. I have made the required changes.

**Comment by Kundan28** [comment]
> @Kundan28 Thank you for reviewing. I have made the required changes.

Okay, I will review all the slides again...

**Comment by imskr** [comment]
Thank you @Kundan28

**Pull request merged**
