### PR TITLE
Fixes #1115 : Replaced Codeacademy Pro tutorial

### LINKED ISSUE #1115: Replace 3 Codecademy Pro links with something free
I audited them, and most are fine.  Here is a list of the links that need replacing:
- [ ] https://www.codecademy.com/courses/asynchronous-javascript/lessons/promises/exercises/understanding-promises in curriculum/javascript/javascript-9.md
- [ ] https://www.codecademy.com/learn/learn-the-command-line in curriculum/command-line/command-line-interface.md
- [ ] https://www.codecademy.com/learn/learn-jquery in curriculum/jquery/jquery.md
- [ ] https://www.codecademy.com/learn/learn-sass in sass/sass.md (low priority)

@alodahl

### PR DESCRIPTION
**Pull request by SimranMakhija7**
Addresses #1115 : Replaced Codeacademy Pro tutorial with freeCodeCamp's YouTube tutorial.

### CODE REVIEW

**Comment by vegetabill** [comment]
@SimranMakhija7 I only see one link changed in this PR for sass. Looks good! 

The issue was asking for all of the links to be replaced. Please push additional commits with those fixes to the same branch and it will show up in this PR.

**Comment by vegetabill** [comment]
@SimranMakhija7 please add those other fixes here. The usual workflow is one issue == one PR, especially for this contents for points but also in general. Splitting it makes it harder to track for the project maintainers.

**Comment by Kundan28** [comment]
@SimranMakhija7 If you want to know how to commit in same branch then have a look at the link below.
https://stackoverflow.com/questions/913012/committing-to-the-same-branch-with-git

**Comment by alodahl** [comment]
Hi @SimranMakhija7 it's ok if you are working slowly, but if we do not hear from you in the next few days we will assume you no longer want to work on this, and the issue will be reassigned.

**Pull request closed without merging**
