### PR TITLE
Update jasmine-testing.md

### PR DESCRIPTION
**Pull request by Lakshita7**
I have added "A quick and complete guide to Mocha testing" blog link in the supplement resources which was missing.
Please let me know if some other changes are required.

### CODE REVIEW

**Comment by manaswinidas** [comment]
@Lakshita7 Is this PR solving an issue? Make sure you add that issue number in the description so it becomes easier to add scores

**Comment by alodahl** [comment]
@lakshita7, could you please move everything from supplemental materials into the supplemental resources section below?

**Comment by alodahl** [comment]
This is for issue #570, correct?

**Comment by Lakshita7** [comment]
@alodahl  this is for #570 

@alodahl yes sure I will move it.

**Comment by alodahl** [comment]
@lakshita7, there should not be a “supplemental materials” section at all; please move everything into “supplemental resources”

**Pull request merged**
