### PR TITLE
Fix Typos in Event Recommender guidelines

### PR DESCRIPTION
**Pull request by vvscode**
https://github.com/Techtonica/curriculum/issues/910

### CODE REVIEW

**Comment by vvscode** [comment]
Sure. Done

**Comment by vvscode** [comment]
@alodahl  the rest are related to code in gist - I'm not sure if forking that gist to make changes is the right approach. But if you assume that should be done - I'm ready

**Comment by alodahl** [comment]
Maybe I mis-titled the issue, but yes, that would be great!

**Comment by vvscode** [comment]
@alodahl  Gist is updated

**Comment by vvscode** [comment]
@alodahl  Actually I see no sense to use gist for such cases as well. Placing code embedded to the document makes everything much more accurate (imho)

**Comment by alodahl** [comment]
Would you mind embedding it, then? I didn’t realize that the gist is now on your account.

**Pull request merged**
