### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by sudocurse**
Adds more info on pen-testing positions, non-engineering in-house jobs, and some research work

### CODE REVIEW

**Comment by alodahl** [comment]
Hi Ankeet, thanks for working on this!  Judy said you might be willing to pick up this issue.  What this outline needs is either major clarification or a redo of the Guided Practice, Independent Practice, Challenge, and Check for understanding exercises. For context, the apprentices will have already completed [Intro to Security](https://github.com/Techtonica/curriculum/blob/master/security/web-security.md) and [Incorporating Auth0](https://github.com/Techtonica/curriculum/blob/master/oauth/o-auth.md) earlier in the year - so Security Roles should be more about available security roles(which you've done, gracias), how to find out if security is the right career path, and what steps they need to take to pursue a career in security.

Would you be comfortable taking this on?

**Comment by judytuna** [comment]
thank you, @sudocurse !!! 🥇

**Comment by alodahl** [comment]
Hi @sudocurse, thanks again for adding to this.  Would you like me to save this issue for you, or should I make it available for other volunteers?

**Comment by sudocurse** [comment]
@alodahl I'll try to sync up with Judy sometime soon to get a better feel for the requirements here. If there's someone else well-positioned to take this on I don't want to be a roadblock.

**Pull request merged**
