### PR TITLE
Update security.md

### LINKED ISSUE #1064: Fix Security Roles contents tables so they don't contain actual content
## Task: Rearrange the content in the first few sections of this outline to be more consistent with our other outlines.

https://github.com/Techtonica/curriculum/blob/main/security/web-security.md

- See our [template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md) for more details about the purposes of each section.

- ###Objectives and Specific Things To Teach sections should contain the objectives of the outline and the things the outline teaches, **not** what an apprentice will learn if they spend years becoming a security engineer.  If you think the present material is valuable, move it into the lesson somewhere; otherwise just remove it. 

- Replace ###Objectives and Specific Things To Teach with relevant lists that summarize the outline itself, near the beginning of the outline, similar to a table of contents. 

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ananyakamboj**
Closes #1064
Changed the objectives and specific things to learn.

### CODE REVIEW

**Comment by Kundan28** [comment]
@ananyakamboj Please link the issue here.

**Comment by ananyakamboj** [comment]
https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/security.md

**Comment by Kundan28** [comment]
@ananyakamboj Please follow [this](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for linking the issue.

**Comment by Kundan28** [comment]
Closes #1064

**Comment by Kundan28** [comment]
> Closes #1064

@ananyakamboj This is the way of linking the issue.

**Comment by Kundan28** [comment]
@ananyakamboj Are you still working on this ?

**Comment by alodahl** [comment]
Hi @ananyakamboj, we haven't heard from you in 8 days.  Please make requested changes within a week or we will close the PR and reassign the issue.

**Comment by Kundan28** [comment]
Removed from the scoresheet too.

**Pull request closed without merging**
