### PR TITLE
translated any mySQL info to PostgreSQL

### LINKED ISSUE #595: Change MySQL to PostgreSQL
Throughout the curriculum, we use different databases. 

This cohort, we're standardizing on using PostgreSQL. 

We need to swap out the mysql connection node module with `pg` in the Eventonica project in these places:

- [ ] Techtonica curriculum: https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md  (most likely finished; just proofread please)
- [ ] Move the Starter code to Techtonica/curriculum from here & translate any mySQL info to PostgreSQL: https://github.com/chulinguy/Eventful-API-test-page 
- [ ] Search the curriculum to ensure everything else is standardized, too.

### PR DESCRIPTION
**Pull request by ANURADHAJHA99**
closes #595

### CODE REVIEW

**Comment by ANURADHAJHA99** [comment]
I moved the Starter code to Techtonica/curriculum/projects & translated any mySQL info to PostgreSQL

**Comment by alodahl** [comment]
Please title your prs with a very short description of the changes. The description should contain the issue number and any more details you think we need to know.

**Comment by alodahl** [comment]
Heres a good example. https://github.com/Techtonica/curriculum/pull/637

**Comment by ANURADHAJHA99** [comment]
hey @alodahl, but i didn't add any pictures in the outlines in the following PR.

**Comment by alodahl** [comment]
this is the list of the files you are committing: https://github.com/Techtonica/curriculum/pull/645/files

**Comment by alodahl** [comment]
This is for postgresQL, @anuradhajha99? I only see logout directions.

**Comment by ANURADHAJHA99** [comment]
@alodahl the following commit is fine https://github.com/Techtonica/curriculum/pull/645/commits/d791815e06059127b315dd2b571628d67e17c031however I don't know how to solve the issue of the previous wrong commits that I committed by mistake. I don't know how to delete the unwanted commit.

**Comment by ANURADHAJHA99** [comment]
https://github.com/Techtonica/curriculum/pull/645/commits/d791815e06059127b315dd2b571628d67e17c031    @alodahl the following commit is fine. However I don't know how to delete the unwanted commits.Please help me.

**Comment by alodahl** [comment]
2 options for that: 1, open a new branch from master and move just the changes that you want. Then make a new PR.     2: if an earlier commit is exactly what you want, there is a way to go back in time to another commit, then force your remote branch to erase its history up to that point - i would google this option or ask on #git_github.

**Comment by alodahl** [comment]
Are you saying you want to commit all of these files to master? Why is there a gitignore if you are just changing MySQL to PostgreSQL?

**Comment by Kundan28** [comment]
Why did you closed the PR ? @ANURADHAJHA99

**Comment by ANURADHAJHA99** [comment]
@Kundan28 I closed the PR because I did a lot of wrong commits so I made a right complete PR in its place.

**Comment by Kundan28** [comment]
I would suggest you that while closing a issue you could reference that new PR here so it could he easy for us to figure out why an PR is closed.

**Comment by ANURADHAJHA99** [comment]
@Kundan28 I will make sure that I follow this in the future.Thank you.

**Comment by Kundan28** [comment]
😊

**Pull request closed without merging**
