### PR TITLE
Added some resources in title Motivation and India

### PR DESCRIPTION
**Pull request by rudri182**
Added some suggestions to motivation and meetups and conferences in India. Some channels and chat 
groups where women can chat safely.

### CODE REVIEW

**Comment by alodahl** [comment]
@manaswinidas thank you! Please add/doublecheck an issue to the scoresheet when you approve.

**Comment by rudri182** [comment]
Can I add some more suggestions to this?

**Comment by manaswinidas** [comment]
Please go ahead @rudri182 !

**Comment by rudri182** [comment]
Can I add a section called "challenges" that women face in tech industry ?

**Comment by alodahl** [comment]
@rudri182 could you find a place for it in this file instead? I’ll make sure you get beginner points for it 🙂 https://github.com/Techtonica/curriculum/blob/master/diversity-inclusion-bias/inclusion.md

**Comment by rudri182** [comment]
Yes sure. Thank you.

**Pull request merged**
