### PR TITLE
Add subtitles to one of the advance command line video

### LINKED ISSUE #702: Add subtitles to Advanced Command Line video
We want to make sure learners have access to subtitles/captioning for the YouTube tutorials they watch.  Please go into the settings of this video and add subtitles:
https://youtu.be/NodKFuUocQY

image

image

Make a comment in this issue when you are finished, and we will find a way for you to make a PR.

Note: Our first priority is English, but if this issue is taken and you'd like to add subtitles in an additional language, add a comment below.

### PR DESCRIPTION
**Pull request by vsharma20v**
Add subtitles/captioning for the YouTube video https://youtu.be/NodKFuUocQY in the English language and also fixed some typo errors in the ethics.md file.
Issue Fixed #702

### CODE REVIEW

**Comment by saberprashant** [comment]
Hi @vsharma20v , it's great that you've added the subtitles and the typos that you fixed is really good work. Please let us know when youtube approve those subtitles and then we will have a look at the video again and after that, we will merge this up. Cheers!

**Comment by vsharma20v** [comment]
> Hi @vsharma20v , it's great that you've added the subtitles and the typos that you fixed is really good work. Please let us know when youtube approve those subtitles and then we will have a look at the video again and after that, we will merge this up. Cheers!

Yes, I will keep track of its acceptance.

**Comment by Kundan28** [comment]
Any update on this ? @vsharma20v

**Comment by vsharma20v** [comment]
> Any update on this? @vsharma20v

It is still in reviewing stage
Screenshot from 2019-04-20 13-38-57

but I'm trying to contact the owner of the video through Facebook and also the youtube help community for speeding the review process.

**Comment by Kundan28** [comment]
I too have send an email to the admin of the channel...

**Comment by vsharma20v** [comment]
@alodahl @Kundan28 @saberprashant 
Finally, my hard work paid off
subtitles are published by Youtube. You can check them.
Today I'm very happy because It's my first contribution to a video subtitle. :man_technologist: :smiley: :fire:

**Comment by alodahl** [comment]
Excellent work!

**Comment by Kundan28** [comment]
> Excellent work!

Could we approve this PR now ?

**Comment by Kundan28** [comment]
I too got the email from the Admin of the channel.

**Pull request merged**
