### PR TITLE
Created 15 automatic tests 45/45

### PR DESCRIPTION
**Pull request by imskr**
Added tests for following assignments:
3/7, 3/8, 4/1, 4/2, 4/3, 4/4, 4/5, 2/21, 2/4, 2/7, 3/1, 4/10

2/5 have not any test cases:

Following assessments are not very clear:
2/6, 2/14, 3/14

Issue #866

### CODE REVIEW

**Comment by alodahl** [comment]
Don't worry about 2/14 or 3/14.  Why can't you do 2/6?

**Comment by alodahl** [comment]
I'm testing the answers of the last students in 1/30, and all their code is failing your tests. Can you double check 1/30?

**Comment by alodahl** [comment]
Can you also double-check:
- that 2/5  and 3/14 either have no automatic tests, or working ones
- the 'sum' test in 2/6

**Comment by alodahl** [comment]
@manaswinidas @praveenscience @saberprashant could someone add these automatic test PRs to the scoresheet?

**Comment by imskr** [comment]
> I'm testing the answers of the last students in 1/30, and all their code is failing your tests. Can you double check 1/30?

In 1/30 there are 2 questions which needs to be solved. And the last student has done only question 1 that's why automatic test is failing. All other students have solved both.

**Comment by imskr** [comment]
> Can you also double-check:
> 
> * that 2/5  and 3/14 either have no automatic tests, or working ones
> * the 'sum' test in 2/6

In 2/5 it is not mentioned which function name to use, so students have used different different names that's why test case is failing. 

In 3/14 there is no test cases.

In 2/6: I have added the test cases but students have used different function names so it is failing test.

**Comment by alodahl** [comment]
That makes sense =)

**Pull request merged**
