### PR TITLE
financial literacy file for review

### PR DESCRIPTION
**Pull request by julie-norris**
outline to financial literacy slides

### CODE REVIEW

**Comment by alodahl** [comment]
This is excellent!  Do any of your links contain a relevant video for financial literacy?

**Comment by julie-norris** [comment]
I did not add any videos but I can if you would like.

I did cut and past my slides into the original slideshow. I hope that was
helpful.

I did want to make just one or two more edits but my permission was changed
to view only.

Julie

**Comment by alodahl** [comment]
It was helpful!  Would you have time to find a good video for us in the next few days?

**Comment by alodahl** [comment]
OOps, I'll change the edit permissions back.

**Comment by julie-norris** [comment]
Thanks. There are just a few things I saw this AM that I want to correct.

I will look for a video and link it to the outline.

**Pull request merged**
