### PR TITLE
Extra folders were removed and links were updated

### PR DESCRIPTION
**Pull request by FrozenGirl-spd**

### CODE REVIEW

**Comment by Kundan28** [comment]
@alodahl Is this PR valid, as one PR is already for the same issue.

**Comment by FrozenGirl-spd** [comment]
@Kundan28  @alodahl  Sorry but the previous PRs on the same issue can be closed. I was new to the workflow of git then.

#1316  is the recent PR where:
1. extra folders were removed.
2. absolute links were converted into relative links and were updated. 
3. readme and other locations in the project was updates.

**Comment by Kundan28** [comment]
> @Kundan28 @alodahl Sorry but the previous PRs on the same issue can be closed. I was new to the workflow of git then.
> 
> #1316 is the recent PR where:
> 
> 1. extra folders were removed.
> 2. absolute links were converted into relative links and were updated.
> 3. readme and other locations in the project was updates.

You have to work on the old one and close this new one.

**Comment by FrozenGirl-spd** [comment]
@Aayush-1999 yep okie! Thankyou!
@Kundan28  yeppie

**Comment by alodahl** [comment]
this cannot be reopened either because the branch was deleted.  Please don't delete upstream branches anymore until something gets merged, or you're giving up on the issue forever.

Submit a new PR, and be careful next time.

**Pull request closed without merging**
