### PR TITLE
Created 15 automatic tests for repl.it classroom

### PR DESCRIPTION
**Pull request by imskr**
created 15 tests for following assignments:
1/28, 1/29, 1/30, 1/31, 2/11, 2/12, 2/13, 2/15, 2/19, 2/20, 2/22, 2/25, 2/26, 2/27(# 27), 2/27(# 75)

Issue #851

### CODE REVIEW

**Comment by Kundan28** [comment]
Which issue have you fixed in this PR ?

**Comment by imskr** [comment]
created automated test cases for JS assignments in repl.it classroom

**Comment by alodahl** [comment]
@imskr always mention your issue number in your description.

**Comment by alodahl** [comment]
I'm just going to review all the assignments at the end, @imskr .

**Pull request merged**
