### PR TITLE
Fixed projected timelines web-security.md

### PR DESCRIPTION
**Pull request by talarsen**
Addresses #1064

### CODE REVIEW

**Comment by alodahl** [comment]
Hi @talarsen, can you change the title to what specifically was changed in  web-security.md?

**Comment by talarsen** [comment]
Hi @alodahl.
Listed below is what I worked on, but I am unsure of how to represent this in the title.
1. Changed the "projected time" section to more specific timeframes with bullet points.  
2. The first link in the prerequisite section is broken. 
3. The rest of the lesson follows the format of the lesson template provide and the issues seem to have already been fixed.
4. In the lesson extension, the Insecure Labs link doesn't provide the learner with information. It is unclear what the learner needs to do once they click on the Insecure Lab link.

**Comment by alodahl** [comment]
Great, thank you!  Can you fix the broken link and its title?  It should be this: https://github.com/Techtonica/curriculum/blob/main/networking-computing/README.md

**Comment by alodahl** [comment]
Re: "The rest of the lesson follows the format of the lesson template provide and the issues seem to have already been fixed.", 
I'm not so sure.  Can you please double check:
1. That apprentices walk away from this outline _knowing_ all the things listed in "Objectives"
2. That apprentices walk away from this outline _familiar with_ all the things listed in "Specific Things to learn".

If this is not the case, we need to change those two sections to actually list what the rest of the lesson provides.

**Comment by alodahl** [comment]
Hi @talarsen , I understand if you are busy during the holidays, but will you be able to work on this more in the next few weeks?

**Comment by talarsen** [comment]
Hi @alodahl. I have worked my way through the lesson. I am confident that apprentices will be able to answer the Check for Understanding questions. The lesson provides more than enough information to answer the questions. The lesson also touches on all of the topics in objectives and specific things to learn. I was not able to complete steps 4-8 in the independent practice because I don't know how to build an HTML form yet. Thank you.

**Pull request merged**
