### PR TITLE
Create modify_slides.md

### PR DESCRIPTION
**Pull request by kichloo**
- [X] 1. https://docs.google.com/presentation/d/1USOZJSzwXmSYepjwrE9r9ky_fmQ8VPE7bshjsBoDsZM
 - [X] 2. https://docs.google.com/presentation/d/1S3BjcLZNjex2_qiA9MdyJOjWZ_qmJ78STbUeDEyHH_8
  - [X] 3. https://docs.google.com/presentation/d/1viDJyLHXVs-VioUEatvWHDZeOCCmPxZNPHzH0C393rg
  - [X] 4. https://docs.google.com/presentation/d/1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI
  - [X] 5. 
https://docs.google.com/presentation/d/1Dcu1q3W3hZIkk0Wa1mG3KBK75vzY2peFel5WNgNyqN0
-  [X] 6. https://docs.google.com/presentation/d/1-TEyN4TTjP9c9WGcThS1jQmVoY4pG-xt9gjbDhJkUTc

### CODE REVIEW

**Comment by kichloo** [comment]
Fixes #1318

**Comment by Kundan28** [comment]
@kichloo Please fix the 5th link.

**Comment by kichloo** [comment]
@Kundan28 Done

**Comment by Kundan28** [comment]
> Change the font family to `Lato` in [this](https://docs.google.com/presentation/d/1S3BjcLZNjex2_qiA9MdyJOjWZ_qmJ78STbUeDEyHH_8) presentation.

Now just fix this.

**Comment by kichloo** [comment]
Now just fix this.

Done

**Comment by Kundan28** [comment]
> @Kundan28 Done

image
Then why is it showing me Arial ?

**Comment by kichloo** [comment]
I only changed the text, not the code

**Comment by Kundan28** [comment]
> I only changed the text, not the code

Now you did.

**Comment by kichloo** [comment]
Yes!

**Comment by kichloo** [comment]
@Kundan28 Thanks!

**Pull request merged**
