### PR TITLE
moves files to apprenticeship-prep folder

### PR DESCRIPTION
**Pull request by atrip10**

### CODE REVIEW

**Comment by vegetabill** [comment]
@atrip10 did you use `git mv` for these files? They look like adds with no deletes. This will just create duplicate files.

Please also search for any existing links inside the repo to these files and update them to their new locations, per the issue instructions. You can use your editor's search or CLI: `ack '/ethics/ethics.md'`

**Comment by atrip10** [comment]
I have made the required changes please review

**Comment by atrip10** [comment]
> Nice work @atrip10
> @alodahl This PR is now ready to be merged.

thank you and so sorry for the delay

**Comment by alodahl** [comment]
Hi @atrip10 , please:
- add "closes #issuenumber" to the description.
- search for any old instances of the file paths, and fix them to reach their new location. for example, search `ethics/ethics.md` and change all of the instances you find to `apprenticeship-prep/ethics.md`

**Comment by Kundan28** [comment]
> search for all of these old links to make sure the project is updated. These are definitely in the README.md, for one.



> search for all of these old links to make sure the project is updated. These are definitely in the README.md, for one.

Oh, I missed it.

**Comment by alodahl** [comment]
hi @atrip10 please make the changes so we can merge.

**Comment by alodahl** [comment]
Hi @atrip10, it’s been a week since we heard from you. Please make the requested changes in the next week, or we will reassign this issue. Don’t be afraid to ask for help here or on slack if you feel stuck.

**Comment by atrip10** [comment]
> Hi @atrip10, it’s been a week since we heard from you. Please make the requested changes in the next week, or we will reassign this issue. Don’t be afraid to ask for help here or on slack if you feel stuck.

I am sorry I had some issues, I am definitely working on it

**Comment by Kundan28** [comment]
> I am sorry I had some issues, I am definitely working on it

Please ping us if you are facing any issues.

**Comment by Kundan28** [comment]
@atrip10 We would assign someone else to this task after this coming weekend so if you are facing any problem please ask for help on slack.

**Comment by alodahl** [comment]
Hi @atrip10 , a shortcut that could still work is:
1. erase the commits you don't like from master. you will probably need `git reset --hard <commitSHA>` to some effect.
2.  Make your fork's master match techtonica/curriculum/master.
3.  `git merge` + name of the branch you do like.
4. Push up your changes.  If it tells you it doesn't match, use `git push --force`.
5. See if this PR now has the changes you want.
6. Next time, make a new branch for your issue instead of making changes directly in master.

Look up any of these steps online, and/or ask on our git channel on slack.  It may seem overwhelming, but breaking it into smaller steps makes it a lot easier. I have not seen you post at all in slack about this and you really should.

**Comment by atrip10** [comment]
I created a new pr, because i was facing errors in merging in this one i hope it's fine?

**Comment by alodahl** [comment]
Did you try my idea?  Did you seek help?

**Comment by alodahl** [comment]
Did you delete the branch? Please don’t do that anymore.

**Pull request closed without merging**
