### PR TITLE
Updated elective lessons and migrated required files

### LINKED ISSUE #1256: Update elective lessons and migrate all to /electives folder
All lesson files listed in the root [README as electives](https://github.com/Techtonica/curriculum#optional--elective-lessons) move those files into a new `/electives` folder.
~SEO: Search Engine Optimization~
- [x] Sass
- [x] Python
~Datetime~
- [x] Data Visualization
- [x] Adding Chai/Mocha Tests to your project
- [x] MongoDB
- [x] Mongoose
- [x] Auth0
- [x] Memoization
- [x] Mobile Development
In addition, add the following files to the elective section in the README and also put them into the /electives folder:

~/agile-development (move the entire folder and all its lessons)~
~/deploying/deploying.md~
- [x] /web-patterns/web-patterns.md
- [x] /databases/database-migrations.md
- [x] /backend/1_intro_to_backend.md
- [x] /optimization/optimization.md

For all moved files, please update all links that exist in the curriculum already to point to their new location. If you any links that are absolute, e.g. use https://github... then convert them to relative links.

### PR DESCRIPTION
**Pull request by FrozenGirl-spd**
Fixes #1256 . Sorry for late response. I was stuck :(

### CODE REVIEW

**Comment by FrozenGirl-spd** [comment]
Is the PR okay?

**Comment by Kundan28** [comment]
> Is the PR okay?

I already suggested the changes to be made.

**Comment by FrozenGirl-spd** [comment]
#1304 does this works?

**Comment by FrozenGirl-spd** [comment]
@alodahl I have sent the PR according to the requested and suggested changes. Can you please check into it!!
#1316

**Comment by Aayush-1999** [comment]
@FrozenGirl-spd , don't create a new pull request for every change. This will create duplicate pull requests for a single issue. Please move your changes of #1316 to this pull request.

**Comment by FrozenGirl-spd** [comment]
How to move the changes?

**Comment by FrozenGirl-spd** [comment]
I am unable to know the branch name. It says unknown repository :(

**Comment by alodahl** [comment]
yes, it looks like that is what you named your branch.

**Comment by Aayush-1999** [comment]
@FrozenGirl-spd try using `git branch -m [old branch name] [new branch name]`

**Comment by FrozenGirl-spd** [comment]
It didn't work. I feel like I have messed somthing up. Bt yeah will be updating. Just working on that. Thank you.
Sounds a lot of learning!

**Comment by alodahl** [comment]
Actually, it looks like you deleted your branch, so I’m not sure there’s any fix for this. I’ll reopen #1316 , but next time ask questions and work to fix the existing branch.

**Comment by alodahl** [comment]
this can't be edited because the branch was deleted. =(

**Pull request closed without merging**
