### PR TITLE
Remove required problems from intro to week of data structures!

### PR DESCRIPTION
**Pull request by alodahl**

### CODE REVIEW

**Comment by Kundan28** [comment]
Which issue is fixed in this PR ?

**Comment by alodahl** [comment]
Just my own change @Kundan28 😁

**Comment by Kundan28** [comment]
Oh. I didn't saw that label. 😁
I am getting some issue with GitHub...earlier also I was not able to see the comment and asked for the issue two times and made you angry.

**Comment by alodahl** [comment]
Not your fault, I just added the label. You didn’t make me angry 😆

**Comment by Kundan28** [comment]
😄

**Pull request merged**
