### PR TITLE
Fixes #1264 - Find and fix link for Assessment 9 objectives

### LINKED ISSUE #1264: Find and fix link for Assessment 9 objectives
https://github.com/Techtonica/curriculum/blob/master/objectives/9.md

Task: Use search or logic to find the new url for the header link in the outline above. You can use the readme or the other assessment links in the objectives folder for guidance.

Make a PR with the fixed link. If the readme is wrong, fix that too.

### PR DESCRIPTION
**Pull request by CipherGirl**
Closes Issue #1264 - Find and fix link for Assessment 9 objectives

Fixed the links. No link found in the README to fix.

### CODE REVIEW

**Comment by CipherGirl** [comment]
@alodahl Is there any work left for me?

**Comment by Kundan28** [comment]
> @alodahl Is there any work left for me?

See the above comment by @alodahl

**Comment by vegetabill** [comment]
@alodahl good catch. 

@CipherGirl can you remove the mongo section and links as that assessment is no longer being used.

**Comment by Kundan28** [comment]
Update in scoresheet.

**Pull request merged**
