### PR TITLE
added

### PR DESCRIPTION
**Pull request by Kumaranupam2020**
added a specific thing to teach

### CODE REVIEW

**Comment by Kundan28** [comment]
@Kumaranupam2020 Please write descriptive tittle for the PR and please mention the issue number in comments.

**Comment by alodahl** [comment]
@Kumaranupam2020 check out the other PRs for examples of how to write title and description.

**Comment by alodahl** [comment]
@Kumaranupam2020

**Comment by Kundan28** [comment]
@Kumaranupam2020 If you need any help you can ask here, we are ready to help.

**Comment by Kumaranupam2020** [comment]
#726 i soved this issue
Is this the way to write description..?

**Comment by Kundan28** [comment]
Description means that you have to explain what you did in the PR.
And write more descriptive title for the PR.

**Comment by Kundan28** [comment]
And #726 is not the issue number, it's the PR number. You have to mention the issue number.

**Comment by Kumaranupam2020** [comment]
Please provide me a link so that i can see how others write in their PR
description section...
Because it's the 1st time i am contributing to open source...

**Comment by Kundan28** [comment]
@Kumaranupam2020 This PR is the perfect way to open a PR.
https://github.com/Techtonica/curriculum/pull/772

**Comment by alodahl** [comment]
@Kumaranupam2020 are you working on this? I don’t know what issue this is solving or what you need to help you finish.  We need to hear from you or we’ll close the PR.

**Comment by Kumaranupam2020** [comment]
No i am not not. Working on this.... U can close it.

**Pull request closed without merging**
