### PR TITLE
Database

### PR DESCRIPTION
**Pull request by yati1998**
Fixes issue #824

### CODE REVIEW

**Comment by yati1998** [comment]
@alodahl yes I have created the new branch.  I am just wondering how come previous commits are added to this branch.

**Comment by yati1998** [comment]
@alodahl  database was the name of my branch . There some issue while commiting. I am working on it. I am thinking to create a new PR.

**Comment by alodahl** [comment]
You need to create a new branch from the most updated MASTER branch.

**Comment by alodahl** [comment]
Hi Yati, can you tell us if we should close this issue? I'm not sure what this one is about.

**Comment by yati1998** [comment]
@alodahl yes you can close this issue.  This was the pr made by mistake.

**Pull request closed without merging**
